version: '3'
services: 
  web: 
    image: httpd
    ports: 
      - "80:80" 
    volumes: 
      - $PWD/jenkins_home:/var/jenkins_home 
    networks: 
      - net 

  db:
    image: mysql:5.7 
    environment: 
      - "MYSQL_ROOT_PASSWORD=1234" 
    volumes: 
      - $PWD/db_data:/var/lib/mysql 
    networks: 
      - net 
